## env
export JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home
export NDK_ROOT=/Users/mj/Library/Android/sdk/ndk/21.2.6472646
export ANDROID_NDK=$NDK_ROOT
export ANDROID_NDK_HOME=$NDK_ROOT
export ANDROID_SDK=/Users/mj/Library/Android/sdk
export ANDROID_SDK_ROOT=$ANDROID_SDK
export QT_HOME=/Users/mj/Qt/5.14.2/clang_64/bin
export QT_TOOLS_HOME=/Users/mj/Qt/Tools/QtInstallerFramework/3.2/bin
export LVHIEI_BIN=$HOME/bin
export LVHIEI_BIN_EXTRA=$LVHIEI_BIN/python:$LVHIEI_BIN/shell
export PATH=$PATH:$ANDROID_SDK:$ANDROID_SDK/platform-tools:$ANDROID_SDK/tools
export PATH=$PATH:$NDK_ROOT:$NDK_ROOT/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin
export PATH=$PATH:$LVHIEI_BIN:$LVHIEI_BIN_EXTRA
export PATH=$PATH:/Users/mj/source/googlesource/depot_tools
export PATH=$PATH:$QT_HOME:$QT_TOOLS_HOME
export HOMEBREW_NO_AUTO_UPDATE=true
export EDITOR=vim
